import { useState, useEffect } from 'react';
import { Plus, Edit, Trash2, Search, Eye, Users } from 'lucide-react';
import Layout from '../shared/Layout';
import Header from '../shared/Header';
import { adminAPI } from '../../services/api';
import SiswaExcelActions from './SiswaExcelActions';

const Siswa = () => {
  const [siswa, setSiswa] = useState([]);
  const [kelas, setKelas] = useState([]);
  const [loading, setLoading] = useState(true);
  const [showForm, setShowForm] = useState(false);
  const [editingId, setEditingId] = useState(null);
  const [searchTerm, setSearchTerm] = useState('');
  const [kelasFilter, setKelasFilter] = useState('');
  const [newCredentials, setNewCredentials] = useState(null);

  const [formData, setFormData] = useState({
    nisn: '',
    nama_lengkap: '',
    jenis_kelamin: '',
    tanggal_lahir: '',
    alamat: '',
    nama_orang_tua: '',
    telepon_orang_tua: '',
    kelas_id: ''
  });

  useEffect(() => {
    loadSiswa();
    loadKelas();
  }, [searchTerm, kelasFilter]);

  const loadSiswa = async () => {
    try {
      const params = {
        sort: 'nama_lengkap',
        order: 'ASC',
        status: 'aktif'
      };
      if (searchTerm) params.search = searchTerm;
      if (kelasFilter) params.kelas_id = kelasFilter;

      const response = await adminAPI.getSiswa(params);
      if (response.success) {
        setSiswa(response.data);
      }
    } catch (error) {
      console.error('Error loading siswa:', error);
      alert('Gagal memuat data siswa');
    } finally {
      setLoading(false);
    }
  };

  const loadKelas = async () => {
    try {
      const response = await adminAPI.getKelas();
      if (response.success) {
        setKelas(response.data);
      }
    } catch (error) {
      console.error('Error loading kelas:', error);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    // Validation
    if (!formData.nisn || !formData.nama_lengkap || !formData.jenis_kelamin) {
      alert('NISN, nama lengkap, dan jenis kelamin wajib diisi');
      return;
    }

    try {
      if (editingId) {
        // Update
        await adminAPI.updateSiswa(editingId, formData);
        alert('Data siswa berhasil diperbarui');
        setNewCredentials(null);
      } else {
        // Create - password auto-generated by backend
        const response = await adminAPI.createSiswa(formData);

        // Show credentials dialog
        if (response.success && response.data.plain_password) {
          setNewCredentials({
            username: response.data.user.username,
            password: response.data.plain_password
          });
        }

        alert('Data siswa berhasil ditambahkan');
      }

      resetForm();
      loadSiswa();
    } catch (error) {
      console.error('Error saving siswa:', error);
      alert(error.response?.data?.message || 'Gagal menyimpan data siswa');
    }
  };

  const handleEdit = (siswaItem) => {
    setEditingId(siswaItem.id);
    setFormData({
      nisn: siswaItem.nisn,
      nama_lengkap: siswaItem.nama_lengkap,
      jenis_kelamin: siswaItem.jenis_kelamin,
      tanggal_lahir: siswaItem.tanggal_lahir || '',
      alamat: siswaItem.alamat || '',
      nama_orang_tua: siswaItem.nama_orang_tua || '',
      telepon_orang_tua: siswaItem.telepon_orang_tua || '',
      kelas_id: siswaItem.kelas_id || ''
    });
    setShowForm(true);
  };

  const handleDelete = async (id) => {
    if (!window.confirm('Yakin ingin menghapus data siswa ini? Akun login siswa juga akan dihapus.')) return;

    try {
      await adminAPI.deleteSiswa(id);
      alert('Data siswa berhasil dihapus');
      loadSiswa();
    } catch (error) {
      console.error('Error deleting siswa:', error);
      alert(error.response?.data?.message || 'Gagal menghapus data siswa');
    }
  };

  const resetForm = () => {
    setFormData({
      nisn: '',
      nama_lengkap: '',
      jenis_kelamin: '',
      tanggal_lahir: '',
      alamat: '',
      nama_orang_tua: '',
      telepon_orang_tua: '',
      kelas_id: ''
    });
    setEditingId(null);
    setShowForm(false);
  };

  if (loading) {
    return (
      <Layout>
        <div className="flex items-center justify-center h-96">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-emerald-600"></div>
        </div>
      </Layout>
    );
  }

  return (
    <Layout>
      <div className="space-y-6">
        <Header title="Data Siswa" subtitle="Kelola data siswa madrasah" />

        {/* Filter and Actions */}
        <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6">
          <div className="flex flex-wrap gap-4 items-center justify-between mb-4">
            <div className="flex gap-3 flex-1 max-w-2xl">
              {/* Search */}
              <div className="relative flex-1">
                <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-5 h-5" />
                <input
                  type="text"
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  placeholder="Cari nama atau NISN..."
                  className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-xl focus:outline-none focus:ring-2 focus:ring-emerald-500"
                />
              </div>

              {/* Kelas Filter */}
              <select
                value={kelasFilter}
                onChange={(e) => setKelasFilter(e.target.value)}
                className="px-4 py-2 border border-gray-300 rounded-xl focus:outline-none focus:ring-2 focus:ring-emerald-500"
              >
                <option value="">Semua Kelas</option>
                {kelas.map((kelasItem) => (
                  <option key={kelasItem.id} value={kelasItem.id}>
                    {kelasItem.nama_kelas}
                  </option>
                ))}
              </select>
            </div>

            <button
              onClick={() => setShowForm(true)}
              className="flex items-center gap-2 px-4 py-2 bg-emerald-600 text-white rounded-xl hover:bg-emerald-700 transition-colors font-medium"
            >
              <Plus className="w-5 h-5" />
              Tambah Siswa
            </button>
          </div>

          {/* Excel Import/Export Actions */}
          <div className="border-t border-gray-200 pt-4">
            <SiswaExcelActions onImportSuccess={loadSiswa} />
          </div>
        </div>

        {/* Credentials Display Modal */}
        {newCredentials && (
          <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
            <div className="bg-white rounded-2xl p-6 max-w-md w-full">
              <h2 className="text-2xl font-bold text-emerald-600 mb-4">Akun Berhasil Dibuat!</h2>
              <p className="text-gray-600 mb-4">Simpan kredensial login berikut:</p>

              <div className="bg-gray-50 rounded-xl p-4 space-y-3 mb-6">
                <div>
                  <label className="text-sm font-medium text-gray-600">Username (NISN):</label>
                  <p className="text-lg font-bold text-gray-800">{newCredentials.username}</p>
                </div>
                <div>
                  <label className="text-sm font-medium text-gray-600">Password (Auto-generated):</label>
                  <p className="text-lg font-bold text-gray-800">{newCredentials.password}</p>
                </div>
              </div>

              <p className="text-sm text-red-600 mb-4">
                ⚠️ Catat password ini! Password tidak akan ditampilkan lagi.
              </p>

              <button
                onClick={() => setNewCredentials(null)}
                className="w-full px-4 py-2 bg-emerald-600 text-white rounded-xl hover:bg-emerald-700 transition-colors font-medium"
              >
                Tutup
              </button>
            </div>
          </div>
        )}

        {/* Form Modal */}
        {showForm && (
          <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4 overflow-y-auto">
            <div className="bg-white rounded-2xl p-6 max-w-2xl w-full my-8">
              <h2 className="text-2xl font-bold text-gray-800 mb-4">
                {editingId ? 'Edit Data Siswa' : 'Tambah Siswa Baru'}
              </h2>

              <form onSubmit={handleSubmit} className="space-y-4">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      NISN <span className="text-red-500">*</span>
                    </label>
                    <input
                      type="text"
                      value={formData.nisn}
                      onChange={(e) => setFormData({ ...formData, nisn: e.target.value })}
                      className="w-full px-4 py-2 border border-gray-300 rounded-xl focus:outline-none focus:ring-2 focus:ring-emerald-500"
                      disabled={editingId}
                    />
                    {!editingId && (
                      <p className="text-xs text-gray-500 mt-1">NISN akan menjadi username login</p>
                    )}
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      Nama Lengkap <span className="text-red-500">*</span>
                    </label>
                    <input
                      type="text"
                      value={formData.nama_lengkap}
                      onChange={(e) => setFormData({ ...formData, nama_lengkap: e.target.value })}
                      className="w-full px-4 py-2 border border-gray-300 rounded-xl focus:outline-none focus:ring-2 focus:ring-emerald-500"
                    />
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      Jenis Kelamin <span className="text-red-500">*</span>
                    </label>
                    <select
                      value={formData.jenis_kelamin}
                      onChange={(e) => setFormData({ ...formData, jenis_kelamin: e.target.value })}
                      className="w-full px-4 py-2 border border-gray-300 rounded-xl focus:outline-none focus:ring-2 focus:ring-emerald-500"
                    >
                      <option value="">Pilih</option>
                      <option value="L">Laki-laki</option>
                      <option value="P">Perempuan</option>
                    </select>
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      Tanggal Lahir
                    </label>
                    <input
                      type="date"
                      value={formData.tanggal_lahir}
                      onChange={(e) => setFormData({ ...formData, tanggal_lahir: e.target.value })}
                      className="w-full px-4 py-2 border border-gray-300 rounded-xl focus:outline-none focus:ring-2 focus:ring-emerald-500"
                    />
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      Kelas
                    </label>
                    <select
                      value={formData.kelas_id}
                      onChange={(e) => setFormData({ ...formData, kelas_id: e.target.value })}
                      className="w-full px-4 py-2 border border-gray-300 rounded-xl focus:outline-none focus:ring-2 focus:ring-emerald-500"
                    >
                      <option value="">Belum ada kelas</option>
                      {kelas.map((kelasItem) => (
                        <option key={kelasItem.id} value={kelasItem.id}>
                          {kelasItem.nama_kelas}
                        </option>
                      ))}
                    </select>
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      Nama Orang Tua
                    </label>
                    <input
                      type="text"
                      value={formData.nama_orang_tua}
                      onChange={(e) => setFormData({ ...formData, nama_orang_tua: e.target.value })}
                      className="w-full px-4 py-2 border border-gray-300 rounded-xl focus:outline-none focus:ring-2 focus:ring-emerald-500"
                    />
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      Telepon Orang Tua
                    </label>
                    <input
                      type="tel"
                      value={formData.telepon_orang_tua}
                      onChange={(e) => setFormData({ ...formData, telepon_orang_tua: e.target.value })}
                      className="w-full px-4 py-2 border border-gray-300 rounded-xl focus:outline-none focus:ring-2 focus:ring-emerald-500"
                    />
                  </div>
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    Alamat
                  </label>
                  <textarea
                    value={formData.alamat}
                    onChange={(e) => setFormData({ ...formData, alamat: e.target.value })}
                    rows={2}
                    className="w-full px-4 py-2 border border-gray-300 rounded-xl focus:outline-none focus:ring-2 focus:ring-emerald-500"
                  />
                </div>

                {!editingId && (
                  <div className="bg-blue-50 border border-blue-200 rounded-xl p-3">
                    <p className="text-sm text-blue-800">
                      <strong>Info:</strong> Password akan di-generate otomatis dan ditampilkan setelah berhasil menyimpan.
                    </p>
                  </div>
                )}

                <div className="flex gap-3 pt-4">
                  <button
                    type="button"
                    onClick={resetForm}
                    className="flex-1 px-4 py-2 border border-gray-300 text-gray-700 rounded-xl hover:bg-gray-50 transition-colors font-medium"
                  >
                    Batal
                  </button>
                  <button
                    type="submit"
                    className="flex-1 px-4 py-2 bg-emerald-600 text-white rounded-xl hover:bg-emerald-700 transition-colors font-medium"
                  >
                    {editingId ? 'Perbarui' : 'Simpan'}
                  </button>
                </div>
              </form>
            </div>
          </div>
        )}

        {/* Siswa Table */}
        <div className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead className="bg-gray-50 border-b border-gray-200">
                <tr>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    NISN
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Nama Lengkap
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    JK
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Kelas
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Username
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Orang Tua
                  </th>
                  <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Aksi
                  </th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-gray-200">
                {siswa.length === 0 ? (
                  <tr>
                    <td colSpan="7" className="px-6 py-12 text-center text-gray-500">
                      Belum ada data siswa
                    </td>
                  </tr>
                ) : (
                  siswa.map((siswaItem) => (
                    <tr key={siswaItem.id} className="hover:bg-gray-50">
                      <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                        {siswaItem.nisn}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                        {siswaItem.nama_lengkap}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-600">
                        {siswaItem.jenis_kelamin}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-600">
                        {siswaItem.kelas?.nama_kelas || '-'}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm">
                        <span className="font-mono bg-gray-100 px-2 py-1 rounded">
                          {siswaItem.user?.username}
                        </span>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-600">
                        {siswaItem.nama_orang_tua || '-'}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                        <div className="flex justify-end gap-2">
                          <button
                            onClick={() => handleEdit(siswaItem)}
                            className="p-2 text-blue-600 hover:bg-blue-50 rounded-lg transition-colors"
                            title="Edit"
                          >
                            <Edit className="w-4 h-4" />
                          </button>
                          <button
                            onClick={() => handleDelete(siswaItem.id)}
                            className="p-2 text-red-600 hover:bg-red-50 rounded-lg transition-colors"
                            title="Hapus"
                          >
                            <Trash2 className="w-4 h-4" />
                          </button>
                        </div>
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </div>

        {/* Info Box */}
        <div className="bg-blue-50 border border-blue-200 rounded-2xl p-4">
          <p className="text-sm text-blue-800">
            <strong>Catatan:</strong> Username siswa menggunakan NISN dan password di-generate otomatis.
            Password hanya ditampilkan saat pertama kali membuat akun siswa.
            Untuk mengubah password, gunakan fitur Reset Password.
          </p>
        </div>
      </div>
    </Layout>
  );
};

export default Siswa;
